# Verion of docker-compose to use
version: '3'

services:
    api:
        container_name: 'flow_api'
        image: 'flow_api'
        build:
            context: ./api #Sets the directory for docker-compose to build.
            dockerfile: ./Dockerfile.dev

        env_file:
            - env/common.dev.env
            - env/api.dev.env
        # Maps port on the local machine to port on Docker image
        ports:
            - '8000:8000'

        volumes:
            # Copy changes made to the project to your image in real-time.
            - ./api:/code
            - flow_media:/code/media
        # Handles the command used to run the project in the Docker container.
        command: sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
    # Creates a volume for the database.
    flow_media:
