# Generated by Django 4.2.1 on 2023-05-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='file',
        ),
    ]
