# The image you are going to inherit your Dockerfile from
FROM python:3.11

# # Necessary, so Docker doesn't buffer the output and that you can see the output 
# # of your application (e.g., Django logs) in real-time.
# ENV PYTHONUNBUFFERED 1

# Make a directory in your Docker image, which you can use to store your source code
RUN mkdir /code

# Set the /code directory as the working directory
WORKDIR /code

# Copies from your local machine's current directory to the code folder 
# in the Docker image
COPY . .

# Copy the requirements.txt file adjacent to the Dockerfile 
# to your Docker image
COPY ./requirements.txt /requirements.txt
# Install the requirements.txt file in Docker image
RUN pip install -r /requirements.txt

# Create a user that can run your container
RUN adduser --disabled-password user

# Switch to the user you just created
USER user